version: '3.2'

services:
  iris:
    image: store/intersystems/iris-community:2019.3.0.309.0
    container_name: iris-community-2019.3
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - ./shared:/shared